services:
  weather2mqtt:
    container_name: weater2mqtt
    image: oitc/weather2mqtt:latest
    restart: "no"
    user: 3985:3985
    environment:
      TZ: Europe/Berlin
      DEBUG: true
      MODE: current
      LATITUDE: 48.72592
      LONGITUDE: 9.11446
      WEATHER_MODELS: icon_d2
      MQTT_SERVER: test.mosquitto.org
      MQTT_PORT: 8883
      MQTT_TLS: true
      MQTT_TLS_INSECURE: false
      MQTT_PROTOCOL_VERSION: 5
      MQTT_TOPIC: github.com/cybcon/docker.weather2mqtt.git/weather
      CACHE_EXPIRY_AFTER_SEC: 10
